name: "Build"
on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { title: "linux"         , host: "ubuntu-latest" , cc: "gcc"     , arch: "x64", conf: "Release" }
          - { title: "windows"       , host: "windows-latest", cc: "vs2022"  , arch: "x64", conf: "Release" }
          - { title: "macos"         , host: "macos-13"      , cc: "clang"   , arch: "x64", conf: "Release" }

    name: "${{matrix.title}} (${{matrix.cc}}, ${{matrix.arch}}, ${{matrix.conf}})"
    runs-on: "${{matrix.host}}"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          path: "source"

      - name: "Checkout AsmJit"
        uses: actions/checkout@v4
        with:
          repository: asmjit/asmjit
          path: "asmjit"

      - name: "Checkout Build Actions"
        uses: actions/checkout@v4
        with:
          repository: build-actions/build-actions
          path: "build-actions"

      - name: "Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Build & Test - Native"
        run: python build-actions/action.py
               --source-dir=source
               --config=source/.github/workflows/build-config.json
               --compiler=${{matrix.cc}}
               --architecture=${{matrix.arch}}
               --problem-matcher=auto
               --build-type=${{matrix.conf}}

      - uses: actions/upload-artifact@v4
        with:
          name: "cult-${{matrix.title}}"
          path: |
            build/cult
            build/Release/cult.exe
